var res = {
    img_logo : "res/images/logo.png",
    btn_back : "res/images/btn_back.png",
    btn_back_press : "res/images/btn_back_press.png",
    btn_close : "res/images/btn_close.png",
    btn_close_press : "res/images/btn_close_press.png",
    btn_hint : "res/images/btn_hint.png",
    btn_hint_press : "res/images/btn_hint_press.png",
    btn_next : "res/images/btn_next.png",
    btn_next_press : "res/images/btn_next_press.png",
    //btn_pause : "res/images/btn_pause.png",
    //btn_pause_press : "res/images/btn_pause_press.png",
    btn_restart : "res/images/btn_restart.png",
    btn_restart_press : "res/images/btn_restart_press.png",
    btn_settings : "res/images/btn_settings.png",
    btn_settings_press : "res/images/btn_settings_press.png",
    pixel_png : "res/images/1.png",
    img_lock_png : "res/images/img_lock.png",
    img_loading_png : "res/images/loading.png",
    pointer_png : "res/images/pointer.png",

    S_PASS: "res/sounds/sfx_pass.mp3",
    S_WRONG: "res/sounds/sfx_wrong.mp3"
};

var sound_move = [
    "res/sounds/piano/1.mp3",
    "res/sounds/piano/2.mp3",
    "res/sounds/piano/3.mp3",
    "res/sounds/piano/4.mp3",
    "res/sounds/piano/5.mp3",
    "res/sounds/piano/6.mp3",
    "res/sounds/piano/7.mp3",
    "res/sounds/piano/8.mp3",
    "res/sounds/piano/9.mp3",
    "res/sounds/piano/10.mp3",
    "res/sounds/piano/11.mp3",
    "res/sounds/piano/12.mp3",
    "res/sounds/piano/13.mp3",
    "res/sounds/piano/14.mp3",
    "res/sounds/piano/15.mp3",
    "res/sounds/piano/16.mp3",
    "res/sounds/piano/17.mp3",
    "res/sounds/piano/18.mp3",
    "res/sounds/piano/19.mp3",
    "res/sounds/piano/20.mp3",
    "res/sounds/piano/21.mp3",
    "res/sounds/piano/22.mp3",
    "res/sounds/piano/23.mp3",
    "res/sounds/piano/24.mp3",
    "res/sounds/piano/25.mp3",
    "res/sounds/piano/26.mp3",
    "res/sounds/piano/27.mp3",
    "res/sounds/piano/28.mp3",
    "res/sounds/piano/29.mp3",
    "res/sounds/piano/30.mp3",
    "res/sounds/piano/31.mp3",
    "res/sounds/piano/32.mp3",
    "res/sounds/piano/33.mp3",
    "res/sounds/piano/34.mp3",
    "res/sounds/piano/35.mp3",
    "res/sounds/piano/36.mp3",
    "res/sounds/piano/37.mp3",
    "res/sounds/piano/38.mp3",
    "res/sounds/piano/39.mp3",
    "res/sounds/piano/40.mp3",
    "res/sounds/piano/41.mp3",
    "res/sounds/piano/42.mp3",
    "res/sounds/piano/43.mp3",
    "res/sounds/piano/44.mp3",
    "res/sounds/piano/45.mp3",
    "res/sounds/piano/46.mp3",
    "res/sounds/piano/47.mp3",
    "res/sounds/piano/48.mp3",
    "res/sounds/piano/49.mp3",
    "res/sounds/piano/50.mp3",
    "res/sounds/piano/51.mp3",
    "res/sounds/piano/52.mp3",
    "res/sounds/piano/53.mp3",
    "res/sounds/piano/54.mp3",
    "res/sounds/piano/55.mp3",
    "res/sounds/piano/56.mp3",
    "res/sounds/piano/57.mp3",
    "res/sounds/piano/58.mp3",
    "res/sounds/piano/59.mp3",
    "res/sounds/piano/60.mp3",
    "res/sounds/piano/61.mp3",
    "res/sounds/piano/62.mp3",
    "res/sounds/piano/63.mp3",
    "res/sounds/piano/64.mp3",
    "res/sounds/piano/65.mp3",
    "res/sounds/piano/66.mp3",
    "res/sounds/piano/67.mp3",
    "res/sounds/piano/68.mp3",
    "res/sounds/piano/69.mp3",
    "res/sounds/piano/70.mp3",
    "res/sounds/piano/71.mp3",
    "res/sounds/piano/72.mp3",
    "res/sounds/piano/73.mp3",
    "res/sounds/piano/74.mp3",
    "res/sounds/piano/75.mp3",
    "res/sounds/piano/76.mp3",
    "res/sounds/piano/77.mp3",
    "res/sounds/piano/78.mp3",
    "res/sounds/piano/79.mp3",
    "res/sounds/piano/80.mp3",
    "res/sounds/piano/81.mp3",
    "res/sounds/piano/82.mp3",
    "res/sounds/piano/83.mp3",
    "res/sounds/piano/84.mp3",
    "res/sounds/piano/85.mp3",
    "res/sounds/piano/86.mp3",
    "res/sounds/piano/87.mp3",
    "res/sounds/piano/88.mp3",
    "res/sounds/piano/88.mp3",
    "res/sounds/piano/89.mp3",
    "res/sounds/piano/90.mp3",
    "res/sounds/piano/91.mp3",
    "res/sounds/piano/92.mp3",
    "res/sounds/piano/93.mp3",
    "res/sounds/piano/94.mp3",
    "res/sounds/piano/95.mp3",
    "res/sounds/piano/96.mp3"
];
var g_resources = [];
for (var i in res) {
    g_resources.push(res[i]);
}
for (var i in sound_move) {
    g_resources.push(sound_move[i]);
}
